name: "service-area-api"

services:
  backend:
    image: ghcr.io/mitay93/service_area_api:master
    env_file:
      - .env
    restart: always
    volumes:
      - ./sockets:/app/sockets/
  db:
    image: postgis/postgis:16-3.4
    env_file:
      - .env
  redis:
    image: redis:7.2.5
    env_file:
      - .env
    restart: always
