name: "service-area-api"

services:
  backend:
    image: <image from github registry when i configure it>
    env_file:
      - .env
    restart: always
    volumes:
      - ./sockets:/tmp/sockets
  db:
    image: postgis/postgis:16-3.4
    env_file:
      - .env
  redis:
    image: redis:7.2.5
    env_file:
      - .env
    restart: always
