# Generated by Django 5.0.6 on 2024-05-27 15:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(  # Enable postgis if it wasn't enabled before
            """CREATE EXTENSION IF NOT EXISTS postgis;""",
            """DROP EXTENSION IF EXISTS postgis;"""
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('language',
                 models.CharField(help_text='ISO 639-1 language code', max_length=2, verbose_name='language')),
                ('currency',
                 models.CharField(help_text='ISO 4217 currency code', max_length=3, verbose_name='currency')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='polygon')),
                ('provider',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas',
                                   to='service_area_api.provider', verbose_name='provider')),
            ],
        ),
    ]
