# Generated by Django 5.0.6 on 2024-05-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_area_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ('-id',)},
        ),
    ]
